name: Java CI with Gradle

on:
  push:
    branches: [ "**" ]

jobs:
   build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:21-jdk
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - run: chmod +x ./gradlew
      - run: ./gradlew clean build publishCurseForge modrinth
        env:
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: Builds
          path: build/libs/*.jar
